// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mindforge-variants/Ember.tsx": () => import("../components/mockups/mindforge-variants/Ember.tsx"),
  "./components/mockups/mindforge-variants/Prism.tsx": () => import("../components/mockups/mindforge-variants/Prism.tsx"),
  "./components/mockups/mindforge-variants/Signal.tsx": () => import("../components/mockups/mindforge-variants/Signal.tsx")
};
